<#import "parts/common.ftlh" as c>
<@c.page>

    <div class="jumbotron">
        <h1>Hello, user</h1>
        <p class="lead">This is a simple internet shop</p>
        <p class="lead">To buy a product click on main</p>
    </div>
    <div class="mt-3">
        <a class="nav-link" href="https://www.youtube.com/channel/UC1g3kT0ZcSXt4_ZyJOshKJQ">Based on materials: LetsCode</a>
    </div>
</@c.page>
